In [9]:
# Import Dependencies
import pandas as pd
import numpy as np
import json
import ast

In [15]:
def load_movies_metadata(file_path):
    df = pd.read_csv(file_path, dtype='unicode')
    json_columns = ['spoken_languages']
    for column in json_columns:
        df[column] = df[column].apply(lambda x: np.nan if pd.isnull(x) else ast.literal_eval(x))
    return df

In [3]:
movie_keywaord = 'ETL Project/keywords.csv.csv'

In [16]:
movies = load_movies_metadata(r"movies_metadata.csv")
movies_df= movies[["id","original_language","spoken_languages"]].dropna()

movies_df.to_csv('movies_df.csv', index=False)
movies_df.head()

      id original_language                                   spoken_languages
0    862                en           [{'iso_639_1': 'en', 'name': 'English'}]
1   8844                en  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2  15602                en           [{'iso_639_1': 'en', 'name': 'English'}]
3  31357                en           [{'iso_639_1': 'en', 'name': 'English'}]
4  11862                en           [{'iso_639_1': 'en', 'name': 'English'}]

In [ ]:
original_language =[]

In [18]:
# prints unique list of languages in the dataset
movie_id = []
language =[]
language_type =[]

for i,row in movies_df.iterrows():
    if row['spoken_languages'] is not np.nan:
        a = row['spoken_languages']
      
        for item in a:
            if item['name'] not in language_type:
                language_type.append(item['name'])
                
language_type_df= pd.DataFrame({"language Type":language_type})
language_type_df.head(20)
#movies_df.head()

   language Type
0        English
1       Français
2        Español
3        Deutsch
4        Pусский
5          Latin
6     Nederlands
7      广州话 / 廣州話
8            普通话
9         Magyar
10         shqip
11      Italiano
12       한국어/조선말
13         فارسی
14         Dansk
15
16           日本語
17       العربية
18      Hrvatski
19      Bosanski

In [26]:
movie_lang_df = pd.merge(movies_df, language_type_df, left_index=True, right_index=True)
movie_lang_df.head(20)
#movie_language_df = movie_lang_df[['id','original_language','language Type']]
#movie_language_df.head()
#movie_language_df.columns = ['Movie Id', 'Language','Language Type']
#movie_language_df.head(10)

,id,original_language,spoken_languages,language Type
0,862,en,"[{'iso_639_1': 'en', 'name': 'English'}]",English
1,8844,en,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Français
2,15602,en,"[{'iso_639_1': 'en', 'name': 'English'}]",Español
3,31357,en,"[{'iso_639_1': 'en', 'name': 'English'}]",Deutsch
4,11862,en,"[{'iso_639_1': 'en', 'name': 'English'}]",Pусский
5,949,en,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Latin
6,11860,en,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Nederlands
7,45325,en,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",广州话 / 廣州話
8,9091,en,"[{'iso_639_1': 'en', 'name': 'English'}]",普通话
9,710,en,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Magyar
10,9087,en,"[{'iso_639_1': 'en', 'name': 'English'}]",shqip
11,12110,en,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Italiano
12,21032,en,"[{'iso_639_1': 'en', 'name': 'English'}]",한국어/조선말
13,10858,en,"[{'iso_639_1': 'en', 'name': 'English'}]",فارسی
14,1408,en,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Dansk
15,524,en,"[{'iso_639_1': 'en', 'name': 'English'}]",
16,4584,en,"[{'iso_639_1': 'en', 'name': 'English'}]",日本語
17,5,en,"[{'iso_639_1': 'en', 'name': 'English'}]",العربية
18,9273,en,"[{'iso_639_1': 'en', 'name': 'English'}]",Hrvatski
19,11517,en,"[{'iso_639_1': 'en', 'name': 'English'}]",Bosanski

In [27]:
movie_language_df = movie_lang_df[['id','original_language','language Type']]
movie_language_df.head(20)

       id original_language language Type
0     862                en       English
1    8844                en      Français
2   15602                en       Español
3   31357                en       Deutsch
4   11862                en       Pусский
5     949                en         Latin
6   11860                en    Nederlands
7   45325                en     广州话 / 廣州話
8    9091                en           普通话
9     710                en        Magyar
10   9087                en         shqip
11  12110                en      Italiano
12  21032                en       한국어/조선말
13  10858                en         فارسی
14   1408                en         Dansk
15    524                en
16   4584                en           日本語
17      5                en       العربية
18   9273                en      Hrvatski
19  11517                en      Bosanski

In [29]:
movie_language_df.columns = ['Movie Id', 'Language','Language Type']
movie_language_df.head(50)

   Movie Id Language     Language Type
0       862       en           English
1      8844       en          Français
2     15602       en           Español
3     31357       en           Deutsch
4     11862       en           Pусский
5       949       en             Latin
6     11860       en        Nederlands
7     45325       en         广州话 / 廣州話
8      9091       en               普通话
9       710       en            Magyar
10     9087       en             shqip
11    12110       en          Italiano
12    21032       en           한국어/조선말
13    10858       en             فارسی
14     1408       en             Dansk
15      524       en
16     4584       en               日本語
17        5       en           العربية
18     9273       en          Hrvatski
19    11517       en          Bosanski
20     8012       en            Română
21     1710       en  Bahasa indonesia
22     9691       en     Bahasa melayu
23    12665       en           svenska
24      451       en          עִבְרִית
25    16420       en             Český
26     9263       en            Polski
27    17015       en           Gaeilge
28      902       fr             Norsk
29    37557       zh        Slovenčina
30     9909       en        Tiếng Việt
31       63       en         Português
32    78802       fr            हिन्दी
33     9598       en            Català
34    47018       en          Íslenska
35      687       en         Afrikaans
36   139405       en            Srpski
37    33689       en             বাংলা
38     9603       en             Wolof
39    34615       en           Cymraeg
40    31174       en           ภาษาไทย
41    11443       en          Latviešu
42    35196       en         Kiswahili
43     9312       en    български език
44      577       en          ελληνικά
45    11861       en            Türkçe
46      807       en             suomi
47    10530       en         Esperanto
48     8391       en       Український
49      629       en           ქართული